name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Run tests
      working-directory: ./test
      run: go test -v
      env:
        UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
        UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        TF_VAR_cloudflare_zone_id: ${{ secrets. CLOUDFLARE_ZONE_ID }}
